// Generated by scripts/sync-nano-fallback-chain.mjs.
// Run npm run sync:nano-fallback after Nano Banana Pro fallback-chain updates.

export const NANO_BANANA_FALLBACK_SNAPSHOT = {
  "sourceApp": "nano-banana-pro",
  "sourceVersion": "6.5.3",
  "syncedAt": "2026-09-24T08:15:12.897Z",
  "sourceFingerprint": "4b154361dae3f8ca554917d657c27ac0e8718dae98a32fd059e84d74bebe5269",
  "sourceFiles": [
    {
      "path": "nano-banana-pro/package.json",
      "bytes": 1503,
      "sha256": "d8c5e9b4b3fcbf092be4bef748ebe2e7d14528a4c5dfb4a8f3e4f007aacfdd7b"
    },
    {
      "path": "nano-banana-pro/src/lib/fallback-chain-history.js",
      "bytes": 13800,
      "sha256": "6bf654f23479375906942ed0424611b662dc24f255333d60b49d91855c75d6cf"
    },
    {
      "path": "nano-banana-pro/src/lib/gemini-model-routes.js",
      "bytes": 464,
      "sha256": "fd75156f38e329e763ef3b724dab2c3a0478b558dac9687d35624f027af8554d"
    },
    {
      "path": "nano-banana-pro/src/config/openai-scenario-models.json",
      "bytes": 3354,
      "sha256": "5a4baeee9403e9cc79cb6bdd1ced64a97c897be1fe86a1c14eb9a028efb92ac0"
    }
  ],
  "chains": {
    "geminiText": {
      "provider": "gemini",
      "sourceFile": "nano-banana-pro/src/lib/gemini-model-routes.js",
      "models": [
        {
          "id": "gemini-3.5-flash",
          "role": "Primary",
          "order": 1
        },
        {
          "id": "gemini-2.5-flash",
          "role": "Backup",
          "order": 2
        },
        {
          "id": "gemini-2.5-pro",
          "role": "Backup",
          "order": 3
        },
        {
          "id": "gemini-flash-latest",
          "role": "Backup",
          "order": 4
        },
        {
          "id": "gemini-pro-latest",
          "role": "Fallback",
          "order": 5
        }
      ]
    },
    "openaiText": {
      "provider": "openai",
      "sourceFile": "nano-banana-pro/src/config/openai-scenario-models.json",
      "priceSnapshotDate": "2026-09-23",
      "priceSnapshotSource": "OpenAI official model pricing",
      "models": [
        {
          "id": "gpt-6-astra",
          "label": "GPT-6 Astra",
          "group": "GPT-6",
          "inputPriceUsdPerM": 10,
          "outputPriceUsdPerM": 50,
          "role": "Primary",
          "order": 1
        },
        {
          "id": "gpt-6-sol",
          "label": "GPT-6 Sol",
          "group": "GPT-6",
          "inputPriceUsdPerM": 2,
          "outputPriceUsdPerM": 10,
          "role": "Backup",
          "order": 2
        },
        {
          "id": "gpt-5.6-sol",
          "label": "GPT-5.6 Sol",
          "group": "GPT-5.6",
          "inputPriceUsdPerM": 4,
          "outputPriceUsdPerM": 20,
          "role": "Backup",
          "order": 3
        },
        {
          "id": "gpt-5.6-terra",
          "label": "GPT-5.6 Terra",
          "group": "GPT-5.6",
          "inputPriceUsdPerM": 2,
          "outputPriceUsdPerM": 12,
          "role": "Backup",
          "order": 4
        },
        {
          "id": "gpt-6-luna",
          "label": "GPT-6 Luna",
          "group": "GPT-6",
          "inputPriceUsdPerM": 0.1,
          "outputPriceUsdPerM": 0.5,
          "role": "Backup",
          "order": 5
        },
        {
          "id": "gpt-5.6-luna",
          "label": "GPT-5.6 Luna",
          "group": "GPT-5.6",
          "inputPriceUsdPerM": 0.2,
          "outputPriceUsdPerM": 1.2,
          "role": "Backup",
          "order": 6
        },
        {
          "id": "gpt-4.1",
          "label": "GPT-4.1",
          "group": "GPT-4.1",
          "inputPriceUsdPerM": 2,
          "outputPriceUsdPerM": 8,
          "role": "Backup",
          "order": 7
        },
        {
          "id": "gpt-4.1-mini",
          "label": "GPT-4.1 mini",
          "group": "GPT-4.1",
          "inputPriceUsdPerM": 0.4,
          "outputPriceUsdPerM": 1.6,
          "role": "Backup",
          "order": 8
        },
        {
          "id": "gpt-4.1-nano",
          "label": "GPT-4.1 nano",
          "group": "GPT-4.1",
          "inputPriceUsdPerM": 0.1,
          "outputPriceUsdPerM": 0.4,
          "role": "Backup",
          "order": 9
        },
        {
          "id": "gpt-4o",
          "label": "GPT-4o",
          "group": "互換",
          "inputPriceUsdPerM": 2.5,
          "outputPriceUsdPerM": 10,
          "role": "Fallback",
          "order": 10
        }
      ]
    }
  },
  "updateWorkflow": "物語バズメーカーのバグフィックスやアップデート時は npm run check:nano-fallback を必ず実行し、差分があれば npm run sync:nano-fallback でこのスナップショットを更新する。"
};
