// Generated by scripts/sync-nano-fallback-chain.mjs.
// Run npm run sync:nano-fallback after Nano Banana Pro fallback-chain updates.

export const NANO_BANANA_FALLBACK_SNAPSHOT = {
  "sourceApp": "nano-banana-pro",
  "syncScope": "openai-only",
  "sourceVersion": "6.9.4",
  "syncedAt": "2026-10-07T05:02:46.099Z",
  "sourceFingerprint": "6a6915d725098949d2090c2d9448bcbe91be8d1f76006d4f22586cad67b634cd",
  "sourceFiles": [
    {
      "path": "nano-banana-pro/package.json",
      "bytes": 1605,
      "sha256": "d7fa33a16edf585c6236083e6bce4589a22aa1c3694df6c5641284435475f4a7"
    },
    {
      "path": "nano-banana-pro/src/lib/fallback-chain-history.js",
      "bytes": 16698,
      "sha256": "1f60a328c35300c988a60c37f1d4cb0e9a803014889a48909f0d63835dbd8dfa"
    },
    {
      "path": "nano-banana-pro/src/lib/gemini-model-routes.js",
      "bytes": 915,
      "sha256": "de1fd370808aea14555af608a4813436918dea0b4e6a6a6e0ae234078ae4c457"
    },
    {
      "path": "nano-banana-pro/src/config/openai-scenario-models.json",
      "bytes": 3896,
      "sha256": "7b7a77e3e834b3c697a37fbc623725cf30effd801fd82816bcc196869b6bcebd"
    }
  ],
  "chains": {
    "geminiText": {
      "provider": "gemini",
      "sourceFile": "nano-banana-pro/src/lib/gemini-model-routes.js",
      "models": [
        {
          "id": "gemini-3.5-flash",
          "role": "Primary",
          "order": 1
        },
        {
          "id": "gemini-2.5-flash",
          "role": "Backup",
          "order": 2
        },
        {
          "id": "gemini-2.5-pro",
          "role": "Backup",
          "order": 3
        },
        {
          "id": "gemini-flash-latest",
          "role": "Backup",
          "order": 4
        },
        {
          "id": "gemini-pro-latest",
          "role": "Fallback",
          "order": 5
        }
      ]
    },
    "openaiText": {
      "provider": "openai",
      "sourceFile": "nano-banana-pro/src/config/openai-scenario-models.json",
      "priceSnapshotDate": "2026-10-07",
      "priceSnapshotSource": "OpenAI official model pricing",
      "models": [
        {
          "id": "gpt-6-astra",
          "label": "GPT-6 Astra",
          "group": "GPT-6",
          "inputPriceUsdPerM": 10,
          "outputPriceUsdPerM": 50,
          "role": "Primary",
          "order": 1
        },
        {
          "id": "gpt-6.1-sol",
          "label": "GPT-6.1 Sol",
          "group": "GPT-6.1",
          "inputPriceUsdPerM": 2,
          "outputPriceUsdPerM": 10,
          "role": "Backup",
          "order": 2
        },
        {
          "id": "gpt-6-sol",
          "label": "GPT-6 Sol",
          "group": "GPT-6",
          "inputPriceUsdPerM": 2,
          "outputPriceUsdPerM": 10,
          "role": "Backup",
          "order": 3
        },
        {
          "id": "gpt-5.6-sol",
          "label": "GPT-5.6 Sol",
          "group": "GPT-5.6",
          "inputPriceUsdPerM": 4,
          "outputPriceUsdPerM": 20,
          "role": "Backup",
          "order": 4
        },
        {
          "id": "gpt-5.6-terra",
          "label": "GPT-5.6 Terra",
          "group": "GPT-5.6",
          "inputPriceUsdPerM": 2,
          "outputPriceUsdPerM": 12,
          "role": "Backup",
          "order": 5
        },
        {
          "id": "gpt-6-luna",
          "label": "GPT-6 Luna",
          "group": "GPT-6",
          "inputPriceUsdPerM": 0.1,
          "outputPriceUsdPerM": 0.5,
          "role": "Backup",
          "order": 6
        },
        {
          "id": "gpt-5.6-luna",
          "label": "GPT-5.6 Luna",
          "group": "GPT-5.6",
          "inputPriceUsdPerM": 0.2,
          "outputPriceUsdPerM": 1.2,
          "role": "Backup",
          "order": 7
        },
        {
          "id": "gpt-4.1",
          "label": "GPT-4.1",
          "group": "GPT-4.1",
          "inputPriceUsdPerM": 2,
          "outputPriceUsdPerM": 8,
          "role": "Backup",
          "order": 8
        },
        {
          "id": "gpt-4.1-mini",
          "label": "GPT-4.1 mini",
          "group": "GPT-4.1",
          "inputPriceUsdPerM": 0.4,
          "outputPriceUsdPerM": 1.6,
          "role": "Backup",
          "order": 9
        },
        {
          "id": "gpt-4.1-nano",
          "label": "GPT-4.1 nano",
          "group": "GPT-4.1",
          "inputPriceUsdPerM": 0.1,
          "outputPriceUsdPerM": 0.4,
          "role": "Backup",
          "order": 10
        },
        {
          "id": "gpt-4o",
          "label": "GPT-4o",
          "group": "互換",
          "inputPriceUsdPerM": 2.5,
          "outputPriceUsdPerM": 10,
          "role": "Fallback",
          "order": 11
        }
      ]
    }
  },
  "updateWorkflow": "物語バズメーカーのバグフィックスやアップデート時は npm run check:nano-fallback を必ず実行し、差分があれば npm run sync:nano-fallback でこのスナップショットを更新する。"
};
