// Generated by scripts/sync-nano-fallback-chain.mjs.
// Run npm run sync:nano-fallback after Nano Banana Pro fallback-chain updates.

export const NANO_BANANA_FALLBACK_SNAPSHOT = {
  "sourceApp": "nano-banana-pro",
  "syncScope": "openai-only",
  "sourceVersion": "6.8.3",
  "syncedAt": "2026-10-04T07:25:41.224Z",
  "sourceFingerprint": "187cce503c066cb6121ed6e0a7d0e27bf1b6ebce2f6fba3e67d6e7fcd6141ea1",
  "sourceFiles": [
    {
      "path": "nano-banana-pro/package.json",
      "bytes": 1542,
      "sha256": "33d541d7e45894089a62de63b415b6c2a13d38c5657b050a0d8cc9fc1bb0b9c3"
    },
    {
      "path": "nano-banana-pro/src/lib/fallback-chain-history.js",
      "bytes": 16326,
      "sha256": "99ccda3f66cc9662fe08c432d7be71c8734eda021a7aed32e1177f268b3cef1e"
    },
    {
      "path": "nano-banana-pro/src/lib/gemini-model-routes.js",
      "bytes": 855,
      "sha256": "be24697131ea677f02159505faca11b63fc9c0ecf59337ff07ff85de72a5b6d3"
    },
    {
      "path": "nano-banana-pro/src/config/openai-scenario-models.json",
      "bytes": 3896,
      "sha256": "6fdb4ae15cea18952117d0342fd70291bd9be5422a106860fce4416c8655945e"
    }
  ],
  "chains": {
    "geminiText": {
      "provider": "gemini",
      "sourceFile": "nano-banana-pro/src/lib/gemini-model-routes.js",
      "models": [
        {
          "id": "gemini-3.5-flash",
          "role": "Primary",
          "order": 1
        },
        {
          "id": "gemini-2.5-flash",
          "role": "Backup",
          "order": 2
        },
        {
          "id": "gemini-2.5-pro",
          "role": "Backup",
          "order": 3
        },
        {
          "id": "gemini-flash-latest",
          "role": "Backup",
          "order": 4
        },
        {
          "id": "gemini-pro-latest",
          "role": "Fallback",
          "order": 5
        }
      ]
    },
    "openaiText": {
      "provider": "openai",
      "sourceFile": "nano-banana-pro/src/config/openai-scenario-models.json",
      "priceSnapshotDate": "2026-09-28",
      "priceSnapshotSource": "OpenAI official model pricing",
      "models": [
        {
          "id": "gpt-6-astra",
          "label": "GPT-6 Astra",
          "group": "GPT-6",
          "inputPriceUsdPerM": 10,
          "outputPriceUsdPerM": 50,
          "role": "Primary",
          "order": 1
        },
        {
          "id": "gpt-6.1-sol",
          "label": "GPT-6.1 Sol",
          "group": "GPT-6.1",
          "inputPriceUsdPerM": 2,
          "outputPriceUsdPerM": 10,
          "role": "Backup",
          "order": 2
        },
        {
          "id": "gpt-6-sol",
          "label": "GPT-6 Sol",
          "group": "GPT-6",
          "inputPriceUsdPerM": 2,
          "outputPriceUsdPerM": 10,
          "role": "Backup",
          "order": 3
        },
        {
          "id": "gpt-5.6-sol",
          "label": "GPT-5.6 Sol",
          "group": "GPT-5.6",
          "inputPriceUsdPerM": 4,
          "outputPriceUsdPerM": 20,
          "role": "Backup",
          "order": 4
        },
        {
          "id": "gpt-5.6-terra",
          "label": "GPT-5.6 Terra",
          "group": "GPT-5.6",
          "inputPriceUsdPerM": 2,
          "outputPriceUsdPerM": 12,
          "role": "Backup",
          "order": 5
        },
        {
          "id": "gpt-6-luna",
          "label": "GPT-6 Luna",
          "group": "GPT-6",
          "inputPriceUsdPerM": 0.1,
          "outputPriceUsdPerM": 0.5,
          "role": "Backup",
          "order": 6
        },
        {
          "id": "gpt-5.6-luna",
          "label": "GPT-5.6 Luna",
          "group": "GPT-5.6",
          "inputPriceUsdPerM": 0.2,
          "outputPriceUsdPerM": 1.2,
          "role": "Backup",
          "order": 7
        },
        {
          "id": "gpt-4.1",
          "label": "GPT-4.1",
          "group": "GPT-4.1",
          "inputPriceUsdPerM": 2,
          "outputPriceUsdPerM": 8,
          "role": "Backup",
          "order": 8
        },
        {
          "id": "gpt-4.1-mini",
          "label": "GPT-4.1 mini",
          "group": "GPT-4.1",
          "inputPriceUsdPerM": 0.4,
          "outputPriceUsdPerM": 1.6,
          "role": "Backup",
          "order": 9
        },
        {
          "id": "gpt-4.1-nano",
          "label": "GPT-4.1 nano",
          "group": "GPT-4.1",
          "inputPriceUsdPerM": 0.1,
          "outputPriceUsdPerM": 0.4,
          "role": "Backup",
          "order": 10
        },
        {
          "id": "gpt-4o",
          "label": "GPT-4o",
          "group": "互換",
          "inputPriceUsdPerM": 2.5,
          "outputPriceUsdPerM": 10,
          "role": "Fallback",
          "order": 11
        }
      ]
    }
  },
  "updateWorkflow": "物語バズメーカーのバグフィックスやアップデート時は npm run check:nano-fallback を必ず実行し、差分があれば npm run sync:nano-fallback でこのスナップショットを更新する。"
};
