import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const main = readFileSync(new URL('../src/main.js', import.meta.url), 'utf8');
const categories = readFileSync(new URL('../src/lib/categories.js', import.meta.url), 'utf8');
const styles = readFileSync(new URL('../src/styles.css', import.meta.url), 'utf8');
const viteConfig = readFileSync(new URL('../vite.config.js', import.meta.url), 'utf8');

assert.match(html, /物語バズメーカー/);
assert.match(html, /物語バズメーカー v1\.2\.1/);
assert.doesNotMatch(html, /日本語圏|Story Maker/);
assert.match(categories, /ストーリー漫画/);
assert.match(categories, /トレンド解説動画/);
assert.doesNotMatch(categories, /日本語圏/);
assert.match(main, /id="api-key"/);
assert.doesNotMatch(main, /id="openai-key"/);
assert.doesNotMatch(main, /id="gemini-key"/);
assert.doesNotMatch(main, /日本語圏/);
assert.match(main, /renderApiConnectPanel/);
assert.match(main, /apiKeyDraft/);
assert.match(main, /他AIへ貼り付ける/);
assert.doesNotMatch(main, /ChatGPTやGemini|Claudeなど/);
assert.match(main, /id="connect-api"/);
assert.match(main, /接続/);
assert.match(main, /id="api-settings"/);
assert.match(main, /API設定/);
assert.match(main, /const APP_VERSION = '1\.2\.1'/);
assert.match(main, /brand-title-row/);
assert.match(main, /version-badge/);
assert.match(main, /api-panel-meta/);
assert.doesNotMatch(main, /maskKey|maskedKey/);
assert.doesNotMatch(main, /sk-proj\.\.\.|AIza\.\.\./);
assert.match(main, /function isStaticPagesRuntime/);
assert.match(main, /searchTrendObservations/);
assert.match(main, /publicTrendSearch\.js/);
assert.doesNotMatch(main, /GitHub Pages版は静的プレビュー|静的プレビュー/);
assert.match(main, /function openApiSettings/);
assert.match(main, /state\.apiPanelOpen = true/);
assert.match(main, /現在の接続/);
assert.match(main, /別のキーを使う場合だけ、新しいキーをこの欄に入力して接続してください。/);
assert.match(main, /id="close-api-settings"/);
assert.match(main, /function closeApiSettings/);
assert.doesNotMatch(main, /id="switch-api"/);
assert.doesNotMatch(main, /function switchApiKey/);
assert.doesNotMatch(main, /id="save-api"/);
assert.doesNotMatch(main, /保存済み/);
assert.doesNotMatch(main, /id="change-api"/);
assert.doesNotMatch(main, /APIキーを変更/);
assert.doesNotMatch(main, /APIキーを保存すると操作できます/);
assert.doesNotMatch(main, /savedApiKey/);
assert.match(main, /function isApiReady/);
assert.doesNotMatch(main, /function isApiDirty/);
assert.doesNotMatch(main, /function syncApiControlState/);
assert.match(main, /function openApiSettings/);
assert.match(main, /state\.apiPanelOpen = true/);
assert.doesNotMatch(main, /id="remember-keys"/);
assert.doesNotMatch(main, /このブラウザに保存する/);
assert.doesNotMatch(main, /localStorage\.setItem/);
assert.match(main, /localStorage\.removeItem\(STORAGE_KEY\)/);
assert.match(main, /autocomplete="new-password"/);
assert.match(main, /data-1p-ignore="true"/);
assert.match(main, /data-bwignore="true"/);
assert.doesNotMatch(main, /class="api-card api-key-card"/);
assert.ok(main.indexOf('renderApiConnectPanel(draftStatus, uiWorking)') < main.indexOf('id="time-window"'));
assert.match(main, /disabledAttr\(isLocked\)/);
assert.match(main, /bindEvents\(isLocked, showApiPanel\)/);
assert.match(main, /if \(isLocked\) return;/);
assert.doesNotMatch(main, /id="run-analysis"/);
assert.match(main, /data-category-id[\s\S]*runProviderDeepening\(\)/);
assert.match(main, /providerBusy:\s*false/);
assert.match(main, /const showApiPanel = !isApiReady\(\) \|\| state\.apiPanelOpen/);
assert.match(main, /const isLocked = !isApiReady\(\) \|\| uiWorking/);
assert.match(main, /function bootstrapApp/);
assert.match(main, /if \(!providerStatus\.provider\.connected\)[\s\S]*focusApiInputSoon\(\)[\s\S]*return;/);
assert.match(main, /renderApiStartGate/);
assert.match(main, /APIキーを入力すると公開Web\/RSS検索を開始します。/);
assert.match(main, /function hasLiveObservations/);
assert.match(main, /if \(!hasLiveObservations\(\)\)[\s\S]*refreshTrendObservations\(\{ runProvider: true \}\)/);
assert.match(main, /function resetAnalysisSessionForApiChange/);
assert.match(main, /resetAnalysisSessionForApiChange\(\)/);
assert.match(main, /state\.providerSummary = null;[\s\S]*state\.planSamples = \{\};[\s\S]*state\.observations = \[\];[\s\S]*state\.report = createReport\(\);/);
assert.match(main, /const runSignature = currentProviderRunSignature\(providerStatus\);/);
assert.match(main, /state\.providerRunSignature = runSignature;/);
assert.match(main, /if \(state\.providerRunSignature !== runSignature\) return;/);
assert.match(main, /if \(isUiWorking\(\)\) return;/);
assert.match(main, /state\.providerBusy = true/);
assert.match(main, /state\.providerBusy = false/);
assert.match(main, /ACTION_MESSAGE_TTL_MS\s*=\s*3500/);
assert.match(main, /function showActionMessage/);
assert.match(main, /window\.setTimeout/);
assert.doesNotMatch(main, /state\.actionMessage\s*=\s*copyMessage/);
assert.match(main, /API稼働中/);
assert.match(main, /使用モデル:/);
assert.match(main, /renderAnalysisBusyBanner/);
assert.match(main, /header-separator/);
assert.ok(main.indexOf('renderAnalysisBusyBanner(report, providerStatus)') > main.indexOf('<header class="topbar">'));
assert.ok(main.indexOf('renderAnalysisBusyBanner(report, providerStatus)') < main.indexOf('</header>'));
assert.ok(main.indexOf('renderActionMessage(state.actionMessage)') > main.indexOf('<div class="header-progress-slot">'));
assert.ok(main.indexOf('renderActionMessage(state.actionMessage)') < main.indexOf('</header>'));
assert.doesNotMatch(main, /api-scroll-locked|scrollTo|body\.style\.top/);
assert.doesNotMatch(main, /progress-steps|busy-progress|根拠シグナルを再検索/);
assert.match(styles, /\.analysis-busy-banner\s*\{[\s\S]*?display:\s*flex;/);
assert.match(styles, /\.brand-title-row\s*\{[\s\S]*?display:\s*flex;/);
assert.match(styles, /\.version-badge\s*\{[\s\S]*?white-space:\s*nowrap;/);
assert.match(styles, /\.api-panel-meta\s*\{[\s\S]*?display:\s*flex;/);
assert.doesNotMatch(styles, /\.analysis-busy-banner\s*\{[\s\S]*?position:\s*fixed/);
assert.match(styles, /\.app-shell\s*\{[\s\S]*?padding:\s*0 22px 22px;/);
assert.match(styles, /\.topbar\s*\{[\s\S]*?position:\s*sticky;/);
assert.match(styles, /\.topbar\s*\{[\s\S]*?top:\s*0;/);
assert.match(styles, /\.topbar\s*\{[\s\S]*?padding-top:\s*22px;/);
assert.doesNotMatch(styles, /\.busy-shell \.topbar/);
assert.match(styles, /\.header-separator\s*\{[\s\S]*?height:\s*3px;/);
assert.match(styles, /\.analysis-busy-banner\s*\{[\s\S]*?border-bottom:\s*3px solid #16181d;/);
assert.match(styles, /\.action-message\s*\{[\s\S]*?border-top:\s*3px solid #16181d;/);
assert.match(styles, /\.action-message\s*\{[\s\S]*?border-bottom:\s*3px solid #16181d;/);
assert.doesNotMatch(styles, /\.api-running-indicator/);
assert.doesNotMatch(styles, /\.progress-steps|\.busy-progress/);
assert.match(styles, /\.header-progress-slot\s*\{[\s\S]*?min-height:\s*34px;/);
assert.match(styles, /\.action-message\s*\{[\s\S]*?flex-wrap:\s*nowrap;/);
assert.doesNotMatch(main, /完了まで操作を止めています|分析結果の混線|一時的に無効化/);
assert.doesNotMatch(main, /renderApiGate/);
assert.doesNotMatch(main, /APIで追加レビュー/);
assert.doesNotMatch(main, /id="reload-api"/);
assert.doesNotMatch(main, /id="reset-api"/);
assert.doesNotMatch(main, /function changeApiKey/);
assert.doesNotMatch(main, /const currentKey = state\.settings\.apiKey/);
assert.match(main, /id="download-docx"/);
assert.match(main, /企画書DOCX保存/);
assert.match(main, /saveExportFile\('docx'\)/);
assert.match(main, /saveExportFile\('json'\)/);
assert.match(main, /saveBytesWithDialog/);
assert.match(main, /showSaveFilePicker/);
assert.match(main, /saveViaNativeDialog/);
assert.match(main, /bytesToBase64/);
assert.match(main, /link\.download = fileName/);
assert.doesNotMatch(main, /保存ファイルにはAPIキーを含めていません/);
assert.doesNotMatch(main, /APIキーは保存ファイルに含めません/);
assert.doesNotMatch(main, /保存先はブラウザの保存ダイアログ/);
assert.doesNotMatch(main, /必要になったら「JSON読み込み」/);
assert.doesNotMatch(main, /file_name/);
assert.doesNotMatch(main, /saveViaLocalServer/);
assert.doesNotMatch(main, /load-saved-json/);
assert.doesNotMatch(main, /noteExportStarted/);
assert.match(main, /id="import-json"/);
assert.match(main, /JSON読み込み/);
assert.match(main, /id="json-file-input"/);
assert.doesNotMatch(main, /上位タグ/);
assert.match(main, /このカテゴリで決めること/);
assert.match(main, /取得元/);
assert.doesNotMatch(main, /安全・差別化・固有名詞の扱い/);
assert.match(main, /class="insight-dashboard"/);
assert.match(main, /分析チャート/);
assert.match(main, /class="plan-toolbar"/);
assert.match(main, /renderBeginnerGuide/);
assert.match(main, /制作ロードマップ/);
assert.match(main, /最初に作るもの/);
assert.match(main, /創作ブリーフ/);
assert.match(main, /物語・台本設計/);
assert.match(main, /プロ向け設計メモ/);
assert.match(main, /読者維持設計/);
assert.match(main, /renderRetentionDesign/);
assert.doesNotMatch(main, /Story Maker|story-maker|連携|routine-panel|storyMakerRoutineNotes|internalRoutineNotes/);
assert.match(main, /主人公/);
assert.match(main, /最初の事件/);
assert.match(main, /data-generate-plan-id/);
assert.match(main, /data-copy-sample-id/);
assert.match(main, /参考文章を生成/);
assert.match(main, /参考文章をコピー/);
assert.match(main, /actionMessage/);
assert.match(main, /renderActionMessage/);
assert.doesNotMatch(main, /state\.providerSummary = copyMessage/);
assert.doesNotMatch(main, /scheduleAutoProviderAnalysis\(providerStatus\)/);
assert.ok(main.indexOf('${renderInsightDashboard(report)}') < main.indexOf('class="report-layout"'));
assert.ok(main.indexOf('renderBeginnerGuide(report, dataTimestamp)') < main.indexOf('class="report-layout"'));
assert.match(main, /function stripProviderPrefix/);
assert.doesNotMatch(main, /summary: successes\.map\(\(item\) => `\$\{providerName\(item\.provider\)\}:/);
assert.doesNotMatch(main, /summary: `\$\{providerStatus\.provider\.name\}:/);
assert.ok(main.indexOf('id="suggest-more"') > main.indexOf('class="plan-section"'));
assert.match(styles, /\.plan-grid\s*\{[\s\S]*?align-items:\s*start;/);
assert.doesNotMatch(styles, /\.prompt-box\s*\{[\s\S]*?margin-top:\s*auto;/);
assert.doesNotMatch(viteConfig, /api\/local-export/);
assert.doesNotMatch(viteConfig, /OUTPUT_DIR|output/);
assert.doesNotMatch(viteConfig, /\?key=/);
assert.match(viteConfig, /x-goog-api-key/);
assert.match(viteConfig, /api\/save-file-dialog/);
assert.match(viteConfig, /SaveFileDialog/);
assert.match(viteConfig, /port:\s*5180/);
