export const PUBLIC_OBSERVATIONS = [
  {
    id: 'story-public-1',
    categoryId: 'story-manga',
    source: 'Google News RSS',
    sourceType: 'public-web-rss',
    title: '漫画の新連載で生活不安を描く作品が話題に',
    snippet: '仕事、評価、家計の不安を日常の小道具で見せる漫画企画への関心が出ている。',
    authorOrChannel: 'Google News RSS',
    tags: ['漫画', '企画', '生活不安', '仕事', '評価', '読者反応'],
    query: '漫画 読み切り トレンド 生活 不安',
    queryUsed: '漫画 読み切り トレンド 生活 不安 / 公開Web/RSS取得1',
    metrics: { rank: 1, recencyScore: 70, sourceWeight: 92 },
    sourceUrl: 'https://news.google.com/story-public-1',
    observedAt: '2026-06-24T10:00:00+09:00',
    publishedAt: '2026-06-24T09:00:00+09:00',
  },
  {
    id: 'story-public-2',
    categoryId: 'story-manga',
    source: 'はてなブックマーク エンタメ',
    sourceType: 'public-web-rss',
    title: '縦読み漫画の第1話は小さな違和感から読ませる',
    snippet: '通知、欄外メモ、検索候補など、1ページ目で意味が分かる異常表示が共有されている。',
    authorOrChannel: 'はてなブックマーク エンタメ',
    tags: ['漫画', '縦読み', '読者反応', 'ページ上の異常表示'],
    query: 'はてなブックマーク エンタメ',
    queryUsed: 'はてなブックマーク エンタメ / 公開Web/RSS取得1',
    metrics: { rank: 2, recencyScore: 66, sourceWeight: 90 },
    sourceUrl: 'https://b.hatena.ne.jp/story-public-2',
    observedAt: '2026-06-24T10:00:00+09:00',
    publishedAt: '2026-06-24T08:00:00+09:00',
  },
  {
    id: 'short-public-1',
    categoryId: 'short-video',
    source: 'Google News RSS',
    sourceType: 'public-web-rss',
    title: 'ショート動画は冒頭の結論と保存理由が伸びる',
    snippet: '生活改善、字幕、コメント誘導を短く置く動画企画が注目されている。',
    authorOrChannel: 'Google News RSS',
    tags: ['ショート動画', '保存', 'コメント', '生活改善'],
    query: 'ショート動画 バズる 企画 日本 保存 コメント',
    queryUsed: 'ショート動画 バズる 企画 日本 保存 コメント / 公開Web/RSS取得1',
    metrics: { rank: 3, recencyScore: 64, sourceWeight: 92 },
    sourceUrl: 'https://news.google.com/short-public-1',
    observedAt: '2026-06-24T10:00:00+09:00',
    publishedAt: '2026-06-24T07:00:00+09:00',
  },
  {
    id: 'short-public-2',
    categoryId: 'short-video',
    source: 'Google Trends RSS',
    sourceType: 'public-web-rss',
    title: 'スマホ時短術が急上昇',
    snippet: '視聴者がすぐ試せる小さな改善と、失敗例へのコメントが集まりやすい。',
    authorOrChannel: 'Google Trends RSS',
    tags: ['ショート動画', '保存', '生活改善', '急上昇'],
    query: 'Google Trends 日本 日次急上昇',
    queryUsed: 'Google Trends 日本 日次急上昇 / 公開Web/RSS取得1',
    metrics: { rank: 4, recencyScore: 72, sourceWeight: 88 },
    sourceUrl: 'https://trends.google.co.jp/short-public-2',
    observedAt: '2026-06-24T10:00:00+09:00',
    publishedAt: '2026-06-24T06:00:00+09:00',
  },
  {
    id: 'explainer-public-1',
    categoryId: 'trend-explainer',
    source: 'はてなブックマーク テクノロジー',
    sourceType: 'public-web-rss',
    title: 'SNSの推薦システムと視聴習慣を分解する記事が伸びる',
    snippet: '短尺動画、推薦、炎上回避、制作手順を説明する需要がある。',
    authorOrChannel: 'はてなブックマーク テクノロジー',
    tags: ['解説', 'トレンド', '視聴習慣', '推薦システム', '短尺動画'],
    query: 'はてなブックマーク テクノロジー',
    queryUsed: 'はてなブックマーク テクノロジー / 公開Web/RSS取得1',
    metrics: { rank: 1, recencyScore: 68, sourceWeight: 88 },
    sourceUrl: 'https://b.hatena.ne.jp/explainer-public-1',
    observedAt: '2026-06-24T10:00:00+09:00',
    publishedAt: '2026-06-24T05:00:00+09:00',
  },
  {
    id: 'explainer-public-2',
    categoryId: 'trend-explainer',
    source: 'Google News RSS',
    sourceType: 'public-web-rss',
    title: 'ショートドラマの視聴習慣を解説する需要',
    snippet: 'なぜ続きが見たくなるのかを、心理と制作形式に分解する企画が求められている。',
    authorOrChannel: 'Google News RSS',
    tags: ['解説', 'トレンド', '視聴習慣', 'ショートドラマ'],
    query: 'ショートドラマ なぜ 人気 日本 解説',
    queryUsed: 'ショートドラマ なぜ 人気 日本 解説 / 公開Web/RSS取得1',
    metrics: { rank: 2, recencyScore: 62, sourceWeight: 92 },
    sourceUrl: 'https://news.google.com/explainer-public-2',
    observedAt: '2026-06-24T10:00:00+09:00',
    publishedAt: '2026-06-24T04:00:00+09:00',
  },
  {
    id: 'explainer-public-3',
    categoryId: 'trend-explainer',
    source: 'YahooニュースRSS IT',
    sourceType: 'public-web-rss',
    title: '生成AIと評価不安を安全に解説する企画が読まれる',
    snippet: '技術そのものより、評価される側の不安と制作への応用を分けて説明する記事が共有されている。',
    authorOrChannel: 'YahooニュースRSS IT',
    tags: ['解説', 'トレンド', '生成AI', '評価', '不安'],
    query: '生成AI 評価 不安 解説 日本',
    queryUsed: '生成AI 評価 不安 解説 日本 / 公開Web/RSS取得1',
    metrics: { rank: 3, recencyScore: 61, sourceWeight: 86 },
    sourceUrl: 'https://news.yahoo.co.jp/explainer-public-3',
    observedAt: '2026-06-24T10:00:00+09:00',
    publishedAt: '2026-06-24T03:30:00+09:00',
  },
  {
    id: 'novel-public-1',
    categoryId: 'long-novel',
    source: 'Google News RSS',
    sourceType: 'public-web-rss',
    title: 'Web小説の長編読者は伏線と章末の問いを重視',
    snippet: '評価制度、未返信、記録文書などを章ごとに回収する長編企画が読者維持に向く。',
    authorOrChannel: 'Google News RSS',
    tags: ['Web小説', '読者維持', '長編', '評価', '伏線'],
    query: 'Web小説 トレンド 日本 読者 維持',
    queryUsed: 'Web小説 トレンド 日本 読者 維持 / 公開Web/RSS取得1',
    metrics: { rank: 1, recencyScore: 60, sourceWeight: 92 },
    sourceUrl: 'https://news.google.com/novel-public-1',
    observedAt: '2026-06-24T10:00:00+09:00',
    publishedAt: '2026-06-24T03:00:00+09:00',
  },
  {
    id: 'novel-public-2',
    categoryId: 'long-novel',
    source: 'はてなブックマーク エンタメ',
    sourceType: 'public-web-rss',
    title: '小説投稿サイトで中長編の関係変化が読まれる',
    snippet: '章末ごとに別人物の痛みを見せ、主人公の誤解がほどける構成が読まれやすい。',
    authorOrChannel: 'はてなブックマーク エンタメ',
    tags: ['Web小説', '読者維持', '長編', '関係変化'],
    query: 'はてなブックマーク エンタメ',
    queryUsed: 'はてなブックマーク エンタメ / 公開Web/RSS取得1',
    metrics: { rank: 2, recencyScore: 58, sourceWeight: 90 },
    sourceUrl: 'https://b.hatena.ne.jp/novel-public-2',
    observedAt: '2026-06-24T10:00:00+09:00',
    publishedAt: '2026-06-24T02:00:00+09:00',
  },
];
